// Inline progressive enhancement for hub tables and the home search. Tables are
// complete server-rendered HTML; without JS they keep the A to Z source order.

// Column sort (the card B pattern): empty cells stay last in both directions.
export const HUB_TABLE_CLIENT = `document.querySelectorAll('[data-hub-table]').forEach(t=>t.addEventListener('click',e=>{let b=e.target.closest('button[data-sort]');if(!b)return;let i=+b.dataset.sort,s=b.dataset.type==='text',d=b.dataset.dir==='1'?-1:1;t.querySelectorAll('button[data-sort]').forEach(x=>{if(x!==b)delete x.dataset.dir});b.dataset.dir=String(d);t.querySelectorAll('th[aria-sort]').forEach(x=>x.removeAttribute('aria-sort'));b.closest('th').setAttribute('aria-sort',d===1?'ascending':'descending');let y=t.tBodies[0];[...y.rows].sort((p,q)=>{let v=p.cells[i].dataset.value??'',w=q.cells[i].dataset.value??'';return v===''?+(w!==''):w===''?-1:d*(s?v.localeCompare(w,'en',{sensitivity:'base'}):+v-+w)}).forEach(r=>y.append(r))}));`;

// "Find a system": the static index (name, id) loads on first focus; matches are
// system names containing the query, names starting with it first, then A to Z.
export const HOME_SEARCH_CLIENT = `(()=>{let f=document.querySelector('[data-find]');if(!f)return;let i=f.querySelector('input'),o=f.querySelector('[data-find-results]'),n=f.querySelector('[data-find-note]'),d=null,p=null,m=[];let load=()=>p||(p=fetch('/search-index.json').then(r=>r.json()).then(j=>d=j).catch(()=>{p=null}));let show=async()=>{await load();let q=i.value.trim().toLowerCase();o.textContent='';m=[];if(!q||!d){n.textContent='';return}m=d.filter(s=>s.name.toLowerCase().includes(q)).sort((a,b)=>(a.name.toLowerCase().startsWith(q)?0:1)-(b.name.toLowerCase().startsWith(q)?0:1)||a.name.localeCompare(b.name,'en',{sensitivity:'base'}));for(let s of m.slice(0,10)){let l=document.createElement('li'),a=document.createElement('a');a.href='/e/'+s.id+'/';a.textContent=s.name;l.append(a);o.append(l)}n.textContent=m.length?(m.length>10?m.length+' matches; showing 10. Type more to narrow.':m.length+(m.length===1?' match.':' matches.')):'No system name matches. Try part of the name.'};i.addEventListener('focus',load);i.addEventListener('input',show);f.addEventListener('submit',e=>{e.preventDefault();show().then(()=>{if(m[0])location.href='/e/'+m[0].id+'/'})})})();`;
