"""gen_redirects - regenerate the public redirects.yaml from web/vercel.json.

web/vercel.json is the redirect config that actually EXECUTES on the host, so it
is the single source of truth. redirects.yaml is the machine-auditable CC0 mirror
(P5). The frozen etl/collect.py still writes a stale genesis redirects.yaml on
every run; this post-step restores the mirror from vercel.json afterwards
(analogous to how taxonomy_v2 restores nodes.json). web-ci's redirects_sync test
asserts the two stay 1:1.

New code, lives OUTSIDE the frozen etl/. Pure standard library.

Usage:
  python collectors/gen_redirects.py            # write redirects.yaml from vercel.json
  python collectors/gen_redirects.py --check    # exit 1 if redirects.yaml is out of sync
"""
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
VERCEL = REPO / "web" / "vercel.json"
YAML = REPO / "redirects.yaml"

HEADER = (
    "# machine-auditable redirects (P5). Mirrors web/vercel.json \"redirects\" 1:1;\n"
    "# web-ci asserts the equivalence so this map can never drift from what executes.\n"
    "# Generated by collectors/gen_redirects.py — edit web/vercel.json, not this file.\n"
    "rules:\n"
)


def render() -> str:
    redirects = json.loads(VERCEL.read_text())["redirects"]
    lines = [HEADER.rstrip("\n")]
    for r in redirects:
        lines.append(f"  - from: '{r['source']}'")
        lines.append(f"    to: '{r['destination']}'")
        lines.append("    status: 301")
    return "\n".join(lines) + "\n"


def main() -> int:
    want = render()
    if "--check" in sys.argv[1:]:
        have = YAML.read_text() if YAML.exists() else ""
        if have == want:
            print("gen_redirects --check: redirects.yaml in sync with vercel.json")
            return 0
        print("gen_redirects --check: redirects.yaml OUT OF SYNC (run gen_redirects.py)")
        return 1
    YAML.write_text(want)
    print(f"gen_redirects: redirects.yaml written from vercel.json ({want.count('- from')} rules)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
